name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        platform: [cpu, cuda]
        dockerfile: ["Dockerfile.cpu", "Dockerfile.cuda"]
        include:
          - platform: cpu
            dockerfile: Dockerfile.cpu
          - platform: cuda
            dockerfile: Dockerfile.cuda
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image (cpu or cuda)
      with:
          context: ./docker
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: false
          tags: |
            backend/${{ matrix.platform }}:${{ github.sha }}
