name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          # x86_64 平台：构建 cpu 版本
          - platform: x86_64
            dockerfile: docker/Dockerfile.cpu
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: false  # 如果你不希望推送，设为 false
          tags: |
            backend/${{ matrix.platform }}:${{ github.sha }}
