name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-24.04
            dockerfile: docker/Dockerfile.cpu
            platform: linux/amd64
          - runs-on: ubuntu-24.04-arm
            dockerfile: docker/Dockerfile.cpu
            platform: linux/arm64
    runs-on: ${{ matrix.runs-on }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Call build template
        uses: ./.github/workflows/build_template.yml
        with:
          runs-on: ${{ matrix.runs-on }}
          dockerfile: ${{ matrix.dockerfile }}
          platform: ${{ matrix.platform }}
