name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          # x86_64 平台：构建 cpu 版本
          - platform: x86_64
            dockerfile: docker/Dockerfile.cpu
            
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platform }}
          push: true  # 如果你不希望推送，设为 false
          tags: |
            ghcr.io/bronya5th/backend${{ matrix.platform }}:${{ github.sha }}
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
